### ISSUE TITLE
Server deafening?!

### ISSUE THREAD

**Issue by kubo6472** [groovy-bot/css-framework#15]
Hi, so by article on your support website, the bot deafens itself, but I haven't found any evidence that that does anything apart from a visual change. Do you have some "proof" that you actually aren't receiving any user bandwidth. jagrosh/musicbot#519 I want it for the dev of this self hosted bot to add it as an config option, I tried looking, but haven't found anything, since everyone is referring back to your article on zendesk.

**Comment by nikammerlaan** [comment]
Hey Kubo, this probably isn't the right place for these kind of questions. Feel free to reach out on our support server. https://discord.gg/groovy

**Comment by kubo6472** [comment]
Hey, thank you. I figured that the best idea was to actually write to discord directly. So they got back, and it's actually saving the bandwidth.
